bin/* /usr/bin
kano_draw /usr/lib/python2.7/dist-packages

out/www/* /usr/share/kano-draw
node_modules/@kano/styles/fonts/* /usr/share/kano-draw/www/www/fonts
resources/icon-set/fonts/icomoon* /usr/share/kano-draw/www/www/fonts
/assets/layout/                   /usr/share/kano-draw/www/www/fonts


kdesktop/Draw.lnk usr/share/kano-desktop/kdesk/kdesktop/
kdesktop/kano-draw.xml /usr/share/mime/packages/
icon/kano-draw.png usr/share/icons/Kano/88x88/apps
icon/locale/es_AR/*.app /usr/share/applications/locale/es_AR/
icon/application-x-kano-draw.png usr/share/icons/Kano/88x88/mimetypes
icon/kano-draw-hover.png usr/share/icons/Kano/88x88/apps
icon/kano-draw.app usr/share/applications
media /usr/share/kano-draw/

kano-content-blacklist/kano-draw.json /usr/share/kano-content/blacklists